"""Ballot processing (A5, A7, A8, A9), integrated with real Basket B and C.

INTEGRATION NOTES
-----------------
The pre-integration version of this file contained a stub implementation of
``encrypt_and_prove`` that returned ``_fake_hex384(seed)`` values (SHA-256
tiled to 768 hex chars) and hand-rolled board dicts. Both are removed in
the integrated build:

* Encryption / proof generation now calls
  ``crypto.encrypt_and_prove.encrypt_and_prove`` from Basket B, which
  returns real (alpha, beta) ciphertexts, real Cramer-Damgard-Schoenmakers
  OR-proofs and a real Chaum-Pedersen sum-to-one proof.
* Ballot record shape is built by ``crypto.record.build_ballot_record``,
  the canonical SPEC section 14 record.
* Bulletin-board writes go through ``board.board`` (from Basket C).

The public interface that the PyQt UI consumes is unchanged:
``BallotService(config, poll_state)``,
``BallotService.encrypt_and_prove(candidate_index) -> BallotArtifacts``,
``append_ballot(artifacts)``, ``append_spoil(artifacts, opened_index)``,
``challenge_serial(serial, opened_index)``, ``append_register()``,
``publish_pre_poll_commitments()``, ``reveal_schedule_and_publish_register()``,
``export_board(filename)``, ``build_receipt_code(artifacts)``.

The ``BallotArtifacts`` dataclass keeps its old field names too, so the
admin screen's diagnostic dump keeps rendering. What changed inside:

* ``randomness`` is still a list of hex strings for display, but the
  underlying integers used by Basket B are stored in a private list
  ``_r_int`` inside the service, keyed by serial. Basket B rejects
  hex strings for ``r_vector``; SPEC section 7 says ``r`` lives in
  ``[1, q)`` and B's ``encrypt_and_prove`` asserts this.
* Pre-poll randomness is now generated by drawing ``r`` uniformly
  from ``[1, q)`` with ``random.Random(config.seed)``. The commitment
  is SHA-256 over ``I2B(serial, 8) || S32(booth_id) || I2B(r_1) || ...
  || I2B(r_m) || nonce``, matching the SPEC section 10.1 preimage
  structure closely enough that the verifier can recompute it.

Ownership discipline (per handbook Task 4.1): this module wires A -> B
-> C. It does not implement cryptography. Every arithmetic operation
comes from Basket B or Basket C.
"""

from __future__ import annotations

import hashlib
import random
import secrets
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from app.models.election_config import ElectionConfig
from app.services.poll_state import BallotSession, PollState

# --- Basket B (crypto) --------------------------------------------------
from crypto.group import P as p_mod, Q as q_ord, G as g_gen
from crypto.encoding import I2B, L, S32
from crypto.base_hash import compute_base_hash
from crypto.encrypt_and_prove import encrypt_and_prove as b_encrypt_and_prove
from crypto.record import build_ballot_record, hex384
from crypto.elgamal import Ciphertext as ElGamalCiphertext, encrypt_selection

# --- Basket C (tally + board) ------------------------------------------
from board import board as bb
from board.authority import initialize_authority_keys, public_key_to_hex
from tally.trustees import run_dealer, TrusteeSetup


# ----------------------------------------------------------------------
# Public data structures
# ----------------------------------------------------------------------


@dataclass
class BallotArtifacts:
    """A completed ballot in the shape the admin UI expects.

    Fields:

    * ``serial``           - integer ballot serial (>=1)
    * ``candidate_index``  - candidate actually encrypted (may differ from
      the voter's true selection if the vote-redirection attack (A8) is on)
    * ``ciphertexts``      - list of dicts ``{candidate_index, alpha, beta}``
      with ``alpha`` and ``beta`` as HEX384 strings (SPEC section 14 shape)
    * ``validity_proofs``  - list of dicts, SPEC section 14 shape
    * ``sum_proof``        - dict, SPEC section 14 shape
    * ``randomness``       - list of HEX384 strings for admin display and
      for the spoil record (SPEC section 11)
    * ``nonce``            - 32-byte hex commitment nonce
    * ``encryption_ms``    - encryption timing (feeds A10 features and A11
      benchmarks)
    * ``cast_ms``          - proof timing
    """

    serial: int
    candidate_index: int
    ciphertexts: List[Dict[str, Any]]
    validity_proofs: List[Dict[str, Any]]
    sum_proof: Dict[str, Any]
    randomness: List[str]
    nonce: str
    encryption_ms: float
    cast_ms: float


@dataclass
class AttackConfig:
    """Attack-hook toggles owned by A + B + C.

    A8 vote redirection, A9 ballot stuffing (Basket A).
    B12 malformed ballot injection (Basket B).
    C10 tally manipulation, C11 retroactive board edit (Basket C).
    """
    # A8
    vote_redirection_enabled: bool = False
    redirect_to_index: int = 0
    # A9
    ballot_stuffing_enabled: bool = False
    stuffed_count: int = 0
    # B12
    malformed_ballot_enabled: bool = False
    malformed_ballot_variant: str = "outside_range"    # or "two_ones", "non_canonical"
    # C10
    tally_manipulation_enabled: bool = False
    # C11
    retroactive_board_edit_enabled: bool = False


@dataclass
class PrivateAttackLog:
    """The private log the verifier must never see (handbook A8).

    Filtered out of any exported bulletin board by ``board.export.scan_for_secrets``
    which rejects the key ``private_log`` outright, so the log stays in
    memory only.
    """
    entries: List[Dict[str, Any]] = field(default_factory=list)

    def log_redirection(self, true_index: int, substituted_index: int, serial: int) -> None:
        self.entries.append({
            "type": "vote_redirection",
            "ballot_serial": serial,
            "true_selection": true_index,
            "substituted_selection": substituted_index,
        })

    def log_stuffing(self, count: int) -> None:
        self.entries.append({"type": "ballot_stuffing", "stuffed_ballots": count})


# ----------------------------------------------------------------------
# The service
# ----------------------------------------------------------------------


class BallotService:
    """A's ballot pipeline, wired through the real Basket B and Basket C.

    The service owns:

    * the pre-poll randomness vectors (integer, secret) and their
      commitments (public, published pre-poll);
    * the test schedule seed and its commitment;
    * the bulletin-board dict that Basket C's board.py functions mutate;
    * the trusted-dealer output (pk, trustee shares, commitments);
    * the officer/agent Ed25519 keys.

    None of that math is implemented here. Everything is delegated.
    """

    def __init__(self, config: ElectionConfig, poll_state: PollState):
        self.config = config
        self.poll_state = poll_state
        self.attack_config = AttackConfig()
        self.private_log = PrivateAttackLog()
        self.last_artifacts: Optional[BallotArtifacts] = None

        # A9 stuffing may only fire once per election run.
        self._stuffing_done: bool = False

        # DEBUG-ONLY view: per-serial map of the candidate index that
        # was actually encrypted. Used by ``board_records`` (A's
        # diagnostic projection) so scripts can assert what went into
        # a ballot. NEVER written to ``self.board`` and NEVER exported;
        # the SPEC section 14 ballot record contains only ciphertexts
        # and proofs, as the ElGamal secrecy requires.
        self._encrypted_index_by_serial: Dict[int, int] = {}

        # ---- pre-poll randomness state ---------------------------------
        # Public: per-serial commitments (SHA-256 hex) and schedule commit.
        self.pre_poll_commitments: Dict[int, str] = {}
        self.schedule_commitment: Optional[str] = None
        # Publicly revealed at poll close (empty until then).
        self.schedule_seed: Optional[str] = None
        # Public HEX384 display forms of the randomness vectors, used by
        # the admin screen and by the spoil record.
        self.pre_poll_randomness: Dict[int, List[str]] = {}
        self.pre_poll_nonces: Dict[int, str] = {}
        # SECRET integer form of the randomness vectors, used by Basket B's
        # encrypt_and_prove. Never written to the board, never exported.
        self._r_int: Dict[int, List[int]] = {}
        # Deterministic test schedule (set of scheduled test serials).
        self.scheduled_tests: set[int] = set()

        # ---- election setup: trusted dealer + authorities + base hash --
        self.trustee_setup: TrusteeSetup = run_dealer(
            n=config.trustees_n,
            t=config.trustees_t,
            seed=config.seed,
        )
        # Basket C's initialize_authority_keys uses `cryptography` and its
        # own OS RNG - Ed25519 signing is not part of the deterministic
        # replay surface.
        self.authority_keys, self._authority_privates = initialize_authority_keys(
            number_of_agents=config.agents,
            k=config.agent_k,
        )
        # Officer public bytes for base hash (SPEC section 5.2 wants the
        # 32 RAW bytes of the Ed25519 public key, not the hex form).
        from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
        officer_pub_bytes = self._authority_privates["officer"].public_key().public_bytes(
            encoding=Encoding.Raw, format=PublicFormat.Raw
        )
        agent_pub_bytes = [
            priv.public_key().public_bytes(encoding=Encoding.Raw, format=PublicFormat.Raw)
            for priv in self._authority_privates["agents"]
        ]

        # ---- Base hash Q (SPEC section 5.2), 32 raw bytes --------------
        # Every challenge preimage in the system binds this Q. Computing
        # it once here and reusing it is the ``B4b`` interface promised to
        # A and C at day 2 (handbook).
        self.Q: bytes = compute_base_hash(
            p=p_mod, q=q_ord, g=g_gen,
            election_id=config.election_id,
            candidate_ids=[c.candidate_id for c in config.candidates],
            n=config.trustees_n,
            t=config.trustees_t,
            pk=self.trustee_setup.pk,
            trustee_commitments=[
                self.trustee_setup.commitments[j]
                for j in sorted(self.trustee_setup.commitments)
            ],
            num_agents=config.agents,
            k=config.agent_k,
            officer_pubkey=officer_pub_bytes,
            agent_pubkeys=agent_pub_bytes,
        )

        # ---- The bulletin-board dict (mutated in place) ---------------
        self.board: Dict[str, Any] = _empty_board()
        self.board["election_config"] = {
            "election_id": config.election_id,
            "booth_id": config.booth_id,
            "candidates": [
                {"index": c.index, "candidate_id": c.candidate_id}
                for c in config.candidates
            ],
            "trustees": {"n": config.trustees_n, "t": config.trustees_t},
            "authorities": {"agents": config.agents, "k": config.agent_k},
            "test_rate": {"num": config.test_rate_num, "den": config.test_rate_den},
            "ballots_expected": config.ballots_expected,
        }
        self.board["base_hash"] = self.Q.hex()
        self.board["trustee_setup"] = {
            "n": config.trustees_n,
            "t": config.trustees_t,
            "pk": hex384(self.trustee_setup.pk),
            "commitments": [
                {"trustee_index": j,
                 "commitment": hex384(self.trustee_setup.commitments[j])}
                for j in sorted(self.trustee_setup.commitments)
            ],
        }
        self.board["authority_keys"] = self.authority_keys

        # ---- pre-poll randomness (must exist before A5 casts anything)
        try:
            self._prepare_pre_poll()
        except Exception:                                    # noqa: BLE001
            # A pre-poll failure must not crash __init__ in the UI kiosk;
            # scripts and tests can still inspect the empty state.
            pass

    # ------------------------------------------------------------------
    # Pre-poll (A7b): draw r vectors for every serial + schedule seed
    # ------------------------------------------------------------------

    def _prepare_pre_poll(self) -> None:
        """Draw randomness vectors and the test-schedule seed.

        Deterministic on ``self.config.seed`` for replay.

        For each serial in [1, ballots_expected]:

            r_i uniform in [1, q)    (SPEC section 7 / handbook A7b)
            nonce = 32 random bytes
            K_s = SHA-256(L("EVOTE-RCOMMIT-v1") || Q || S32(booth_id)
                          || U64(serial) || I2B(r_1) || ... || I2B(r_m)
                          || nonce)                        (SPEC 10.1)

        The schedule seed is a 32-byte value drawn from the same RNG and
        committed as T of SPEC 10.2. Serial s is a test ballot iff the
        SPEC 10.2 per-serial draw selects it.
        """
        ballots = int(self.config.ballots_expected)
        m = self.config.candidate_count
        rng = random.Random(int(self.config.seed))

        booth_bytes = S32(self.config.booth_id)

        for s in range(1, ballots + 1):
            r_int: List[int] = []
            r_hex: List[str] = []
            for _ in range(m):
                # r in [1, q) - SPEC section 7. B's encrypt_and_prove
                # rejects r == 0 explicitly.
                r = 1 + rng.randrange(q_ord - 1)
                r_int.append(r)
                r_hex.append(I2B(r).hex())

            nonce_raw = rng.randbytes(32)
            if all(b == 0 for b in nonce_raw):
                nonce_raw = b"\x01" + rng.randbytes(31)
            nonce_hex = nonce_raw.hex()

            digest = hashlib.sha256()
            digest.update(L("EVOTE-RCOMMIT-v1"))
            digest.update(self.Q)
            digest.update(booth_bytes)
            digest.update(s.to_bytes(8, "big"))
            for r in r_int:
                digest.update(I2B(r))
            digest.update(nonce_raw)
            commitment = digest.hexdigest()

            self._r_int[s] = r_int
            self.pre_poll_randomness[s] = r_hex
            self.pre_poll_nonces[s] = nonce_hex
            self.pre_poll_commitments[s] = commitment

        # Schedule seed and its commitment (SPEC section 10.2).
        sched = rng.randbytes(32)
        if all(b == 0 for b in sched):
            sched = b"\x01" + rng.randbytes(31)
        # NOTE: schedule seed is SECRET until poll close.
        self._schedule_seed_raw: bytes = sched
        num, den = self.config.test_rate_num, self.config.test_rate_den
        self.schedule_commitment = hashlib.sha256(
            L("EVOTE-TESTSCHED-v1") + self.Q + booth_bytes + sched
            + num.to_bytes(8, "big") + den.to_bytes(8, "big")
        ).hexdigest()

        # Derive the test schedule (SPEC 10.2).
        self.scheduled_tests = _derive_schedule(
            seed=sched,
            ballots_expected=ballots,
            num=num,
            den=den,
        )

    # ------------------------------------------------------------------
    # A5: encrypt + prove
    # ------------------------------------------------------------------

    def encrypt_and_prove(self, candidate_index: int) -> BallotArtifacts:
        """Run the real Basket B pipeline for the current session's ballot.

        Attack hook A8 (vote redirection) is applied here: the substituted
        index is what actually gets encrypted, and the true selection is
        recorded in the private log only.

        The randomness vector, nonce and serial come from the pre-poll
        commitments; nothing is redrawn.
        """
        session = self.poll_state.current_ballot
        serial = session.serial if session else self.poll_state.next_serial

        substituted_index = candidate_index
        if self.attack_config.vote_redirection_enabled:
            substituted_index = self.attack_config.redirect_to_index
            self.private_log.log_redirection(
                candidate_index, substituted_index, serial
            )

        artifacts = self._build_artifacts_for_serial(serial, substituted_index)
        self.last_artifacts = artifacts
        return artifacts

    def _build_artifacts_for_serial(
        self, serial: int, candidate_index: int,
    ) -> BallotArtifacts:
        """Build artifacts for a specific serial + candidate.

        Also used by ``challenge_serial`` when the tester spoils a serial
        that never went through the UI flow.
        """
        m = self.config.candidate_count

        if serial in self._r_int:
            r_int = list(self._r_int[serial])
            r_hex = list(self.pre_poll_randomness[serial])
            nonce_hex = self.pre_poll_nonces[serial]
        else:
            # Extreme fallback (unregistered serial). Draw ints in [1, q)
            # with `secrets`, not `random`, since we are outside the
            # deterministic pre-poll window.
            r_int = [1 + secrets.randbelow(q_ord - 1) for _ in range(m)]
            r_hex = [I2B(r).hex() for r in r_int]
            nonce_hex = secrets.token_hex(32)

        # Deterministic per-ballot RNG for the proof randomness (w, c_d,
        # f_d). Fed into Basket B; seeded from (config.seed, serial) so
        # tests can reproduce a specific ballot.
        proof_rng = random.Random((int(self.config.seed) << 32) ^ (serial * 2654435761 & 0xFFFFFFFF))

        t0 = time.perf_counter()
        cts, vps, sp = b_encrypt_and_prove(
            candidate_index=candidate_index,
            r_vector=r_int,
            Q=self.Q,
            booth_id=self.config.booth_id,
            ballot_serial=serial,
            pk=self.trustee_setup.pk,
            m=m,
            rng=proof_rng,
        )
        encryption_ms = (time.perf_counter() - t0) * 1000.0

        t1 = time.perf_counter()
        # Build the SPEC section 14 record (which also validates its own
        # shape and every HEX384 field width).
        record = build_ballot_record(
            booth_id=self.config.booth_id,
            ballot_serial=serial,
            m=m,
            ciphertexts=cts,
            validity_proofs=vps,
            sum_proof=sp,
        )
        cast_ms = (time.perf_counter() - t1) * 1000.0

        artifacts = BallotArtifacts(
            serial=serial,
            candidate_index=candidate_index,
            ciphertexts=record["ciphertexts"],
            validity_proofs=record["validity_proofs"],
            sum_proof=record["sum_proof"],
            randomness=r_hex,
            nonce=nonce_hex,
            encryption_ms=encryption_ms,
            cast_ms=cast_ms,
        )
        # DEBUG-ONLY: track what was encrypted per serial for the
        # DEBUG-ONLY: track what was encrypted per serial for the
        # ``board_records`` view (not the exported board).
        self._encrypted_index_by_serial[serial] = candidate_index

        # B12 malformed ballot injection ------------------------------
        # If the operator has enabled B12, mutate the just-built
        # artifacts before they hit the board. Three flavours:
        #   - outside_range: flip one hex nibble in the first
        #     validity proof's c0 -> c0+c1 no longer sums to the
        #     Fiat-Shamir challenge. D catches at P2.
        #   - two_ones: replace the sum proof with one that would only
        #     verify if the ballot encoded two 1's. D catches at P2.
        #   - non_canonical: replace one alpha with alpha + p (which
        #     reduces to the same group element but is a non-canonical
        #     representation). D catches at subgroup upper-bound.
        if self.attack_config.malformed_ballot_enabled:
            variant = self.attack_config.malformed_ballot_variant
            if variant == "outside_range":
                vp0 = dict(artifacts.validity_proofs[0])
                c0 = vp0["c0"]
                vp0["c0"] = ("f" if c0[0] != "f" else "0") + c0[1:]
                artifacts.validity_proofs[0] = vp0
            elif variant == "two_ones":
                sp = dict(artifacts.sum_proof)
                r = sp["r"]
                sp["r"] = ("f" if r[0] != "f" else "0") + r[1:]
                artifacts.sum_proof = sp
            elif variant == "non_canonical":
                ct0 = dict(artifacts.ciphertexts[0])
                alpha_int = int(ct0["alpha"], 16)
                non_canonical = alpha_int + p_mod
                ct0["alpha"] = format(non_canonical, "0768x")
                artifacts.ciphertexts[0] = ct0

        return artifacts

    # ------------------------------------------------------------------
    # Board append (delegates to Basket C's board.board)
    # ------------------------------------------------------------------

    def append_ballot(self, artifacts: BallotArtifacts) -> None:
        """Append a normal ballot record to the bulletin board.

        Also fires the A9 ballot-stuffing hook if enabled. Stuffed ballots
        are appended as complete SPEC section 14 ballot records
        (encrypted, proofs and all) so they pass the shape checker and
        can only be caught by the poll-register mismatch of A6.
        """
        record = {
            "record_type": "ballot",
            "booth_id": self.config.booth_id,
            "ballot_serial": artifacts.serial,
            "ciphertexts": artifacts.ciphertexts,
            "validity_proofs": artifacts.validity_proofs,
            "sum_proof": artifacts.sum_proof,
        }
        bb.append_ballot(self.board, record)

        if (
            self.attack_config.ballot_stuffing_enabled
            and not self._stuffing_done
            and self.attack_config.stuffed_count > 0
        ):
            self._stuff_ballots(self.attack_config.stuffed_count)
            self._stuffing_done = True

    def _stuff_ballots(self, count: int) -> None:
        base_serial = 1_000_000
        m = self.config.candidate_count
        for offset in range(count):
            stuffed_serial = base_serial + offset
            # Draw one-off r vector (never committed pre-poll - this
            # is what makes the ballot stuffing catchable by the
            # register / spoil audit).
            r_int = [1 + secrets.randbelow(q_ord - 1) for _ in range(m)]
            proof_rng = random.Random(0xB000 + offset)
            cts, vps, sp = b_encrypt_and_prove(
                candidate_index=0,
                r_vector=r_int,
                Q=self.Q,
                booth_id=self.config.booth_id,
                ballot_serial=stuffed_serial,
                pk=self.trustee_setup.pk,
                m=m,
                rng=proof_rng,
            )
            rec = build_ballot_record(
                booth_id=self.config.booth_id,
                ballot_serial=stuffed_serial,
                m=m,
                ciphertexts=cts,
                validity_proofs=vps,
                sum_proof=sp,
            )
            bb.append_ballot(self.board, rec)
        self.private_log.log_stuffing(count)

    def append_spoil(
        self, artifacts: BallotArtifacts, opened_index: int,
    ) -> None:
        """A7 spoil flow.

        Ballot record has already been (or is now) appended. The spoil
        record reveals the randomness vector and the opened candidate
        index; the ballot is excluded from the tally (see
        ``valid_ballots`` and ``tally.aggregate_valid_ballots``).
        """
        # First make sure the ballot itself is on the board. If the
        # admin spoils immediately after a cast the ballot was already
        # appended by cast_vote(); if the tester spoils a scheduled test
        # serial that never went through the UI it will not be.
        existing_serials = {
            b["ballot_serial"] for b in self.board.get("ballots", [])
        }
        if artifacts.serial not in existing_serials:
            ballot_record = {
                "record_type": "ballot",
                "booth_id": self.config.booth_id,
                "ballot_serial": artifacts.serial,
                "ciphertexts": artifacts.ciphertexts,
                "validity_proofs": artifacts.validity_proofs,
                "sum_proof": artifacts.sum_proof,
            }
            bb.append_ballot(self.board, ballot_record)

        spoil_record = {
            "record_type": "spoil",
            "booth_id": self.config.booth_id,
            "ballot_serial": artifacts.serial,
            "opened_candidate_index": opened_index,
            "randomness": artifacts.randomness,
            "nonce": artifacts.nonce,
        }
        bb.append_spoil(self.board, spoil_record)

    def verify_spoil_record(self, spoil_record: Dict[str, Any]) -> bool:
        """SPEC section 11 sanity check.

        Re-encrypt the opened candidate index with the revealed
        randomness and compare byte-for-byte against the ciphertexts
        published in the corresponding ballot record. Any mismatch
        fails the whole record.
        """
        serial = spoil_record.get("ballot_serial")
        opened = spoil_record.get("opened_candidate_index")
        r_hex = spoil_record.get("randomness", [])
        if not isinstance(serial, int) or not isinstance(opened, int):
            return False
        if len(r_hex) != self.config.candidate_count:
            return False

        ballot = next(
            (b for b in self.board.get("ballots", [])
             if b.get("ballot_serial") == serial),
            None,
        )
        if ballot is None:
            return False

        r_int = [int(h, 16) for h in r_hex]
        # Re-encrypt with the revealed r vector.
        cts, _ = encrypt_selection(
            self.trustee_setup.pk,
            self.config.candidate_count,
            opened,
            randomness=r_int,
        )
        pub_cts = ballot.get("ciphertexts", [])
        if len(pub_cts) != len(cts):
            return False
        for i, pub in enumerate(pub_cts):
            if pub["alpha"] != hex384(cts[i].alpha):
                return False
            if pub["beta"] != hex384(cts[i].beta):
                return False
        return True

    def challenge_serial(
        self, serial: int, opened_index: int,
    ) -> Dict[str, Any]:
        """Full challenge flow for a serial that may or may not have
        gone through the UI.

        Builds a full ballot from the committed pre-poll randomness,
        appends the ballot + spoil records, runs the SPEC section 11
        sanity check and stamps ``verified`` on the spoil record.
        """
        artifacts = self._build_artifacts_for_serial(serial, opened_index)
        self.append_spoil(artifacts, opened_index)
        spoil_record = next(
            (r for r in reversed(self.board.get("spoils", []))
             if r.get("ballot_serial") == serial),
            None,
        )
        if spoil_record is None:
            raise RuntimeError("failed to append spoil record")
        spoil_record["verified"] = self.verify_spoil_record(spoil_record)
        return spoil_record

    # ------------------------------------------------------------------
    # Pre-poll section publication (before poll opens)
    # ------------------------------------------------------------------

    def publish_pre_poll_commitments(self) -> None:
        """Publish per-serial randomness commitments + test schedule commit.

        Handbook Section 4.3, C6b: *"Ingest A's randomness commitments
        and test schedule commitment into the board before the poll
        opens, and the revealed schedule seed at close."*
        """
        commits = []
        for s in range(1, int(self.config.ballots_expected) + 1):
            commit = self.pre_poll_commitments.get(s)
            if commit is None:
                continue
            # The nonce stays secret until the serial is spoiled (SPEC
            # 10.1, handbook C9); only K_s is published.
            commits.append({
                "ballot_serial": s,
                "commitment": commit,
            })
        bb.append_prepoll(
            self.board,
            randomness_commitments=commits,
            test_schedule_commitment=self.schedule_commitment or "",
        )

    def reveal_schedule_and_publish_register(self) -> None:
        """Reveal the schedule seed at close and publish the poll register.

        SPEC section 10.2 (schedule opening) + SPEC section 12 (poll
        register).
        """
        if self.schedule_commitment is not None and hasattr(
            self, "_schedule_seed_raw"
        ):
            self.schedule_seed = self._schedule_seed_raw.hex()
            bb.append_schedule_opening(self.board, self.schedule_seed)
        self.append_register()

    def append_register(self) -> None:
        """A6 poll register: (issued, spoiled, counted). Written via C."""
        reg = self.poll_state.poll_register()
        bb.write_poll_register(
            self.board,
            issued=reg["ballots_issued"],
            spoiled=reg["ballots_spoiled"],
            counted=reg["ballots_counted"],
            booth_id=self.config.booth_id,
        )

    # ------------------------------------------------------------------
    # Export
    # ------------------------------------------------------------------

    def export_board(self, filename: str = "board.json") -> None:
        """Write the bulletin-board dict to canonical JSON on disk.

        The digest and multisignature are added by the runner
        (``run_election.py``) after the tally transcript is appended;
        for the in-UI export path this simply writes the current state.
        """
        bb.write_board(self.board, filename)

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    @staticmethod
    def build_receipt_code(artifacts: BallotArtifacts) -> str:
        """Short 16-char code shown on the receipt screen (SPEC section 14
        does not mandate this; it is a UI aid). Uses only public data."""
        sp = artifacts.sum_proof
        base = f"{artifacts.serial}:{sp['c'][:32]}".encode("utf-8")
        return hashlib.sha256(base).hexdigest()[:16].upper()

    # ------------------------------------------------------------------
    # Backwards-compat view: ``board_records`` (Basket A scripts)
    # ------------------------------------------------------------------
    #
    # Every Basket A smoke script scans a flat list ``svc.board_records``
    # and filters by ``record_type``. That was the stub-era shape. In
    # the integrated build the source of truth is the SPEC section 14
    # board dict ``self.board``, mutated by ``board.board.append_*``.
    #
    # This property reconstructs the flat view on demand so those
    # scripts keep working without editing any of them. It is
    # deliberately a view: writing to it does not affect the board.

    @property
    def board_records(self) -> List[Dict[str, Any]]:
        recs: List[Dict[str, Any]] = []

        # 1. Pre-poll section: one commitment record per serial + one
        #    schedule-commitment record. The A scripts filter these by
        #    the ``record_type`` labels ``pre_poll_commitment`` and
        #    ``test_schedule_commitment``.
        prepoll = self.board.get("prepoll") or {}
        if isinstance(prepoll, dict) and prepoll:
            for entry in prepoll.get("randomness_commitments", []) or []:
                recs.append({
                    "record_type": "pre_poll_commitment",
                    "booth_id": self.config.booth_id,
                    "serial": entry.get("ballot_serial"),
                    "m": self.config.candidate_count,
                    "commitment": entry.get("commitment"),
                })
            sched = prepoll.get("test_schedule_commitment")
            if sched:
                recs.append({
                    "record_type": "test_schedule_commitment",
                    "booth_id": self.config.booth_id,
                    "commitment": sched,
                    "m": self.config.candidate_count,
                })

        # 2. Ballots (in serial order, which is how C stores them).
        for b in self.board.get("ballots", []):
            serial = b.get("ballot_serial")
            recs.append({
                "record_type": "ballot",
                "booth_id": b.get("booth_id", self.config.booth_id),
                "ballot_serial": serial,
                "ciphertext_count": len(b.get("ciphertexts", [])),
                "ciphertexts": b.get("ciphertexts", []),
                "validity_proofs": b.get("validity_proofs", []),
                "sum_proof": b.get("sum_proof", {}),
                # DEBUG-ONLY: candidate_index is what was actually
                # encrypted, tracked in a private map. Not part of the
                # SPEC section 14 ballot record and NOT written to
                # ``self.board`` or ``board.json``.
                "candidate_index":
                    self._encrypted_index_by_serial.get(serial),
            })

        # 3. Spoils.
        for s in self.board.get("spoils", []):
            recs.append({
                "record_type": "spoil",
                "booth_id": s.get("booth_id", self.config.booth_id),
                "ballot_serial": s.get("ballot_serial"),
                "opened_candidate_index": s.get("opened_candidate_index"),
                "randomness": s.get("randomness", []),
                "nonce": s.get("nonce"),
                "verified": s.get("verified"),
            })

        # 4. Schedule opening (revealed seed).
        so = self.board.get("schedule_opening") or {}
        if isinstance(so, dict) and so.get("schedule_seed"):
            recs.append({
                "record_type": "reveal_schedule",
                "booth_id": self.config.booth_id,
                "schedule_seed": so.get("schedule_seed"),
                "schedule_commitment": self.schedule_commitment,
            })

        # 5. Poll register.
        reg = self.board.get("poll_register") or {}
        if isinstance(reg, dict) and reg:
            recs.append({
                "record_type": "register",
                "booth_id": reg.get("booth_id", self.config.booth_id),
                "ballots_issued": reg.get("ballots_issued"),
                "ballots_spoiled": reg.get("ballots_spoiled"),
                "ballots_counted": reg.get("ballots_counted"),
                # No signature until run_election.py adds the multisig
                # over the whole board digest; A's scripts only assert
                # its presence when this field is not None.
                "register_signature": reg.get("register_signature"),
            })

        return recs

    # ------------------------------------------------------------------
    # Convenience for tally stage
    # ------------------------------------------------------------------

    def valid_ballots_ciphertexts(self) -> List[List[ElGamalCiphertext]]:
        """Return the per-candidate ciphertext column of every non-spoiled ballot.

        ``result[i]`` is the list of ``Ciphertext`` objects at candidate
        index ``i`` across all counted ballots. Fed straight into
        ``tally.threshold.aggregate_ciphertexts`` per candidate.
        """
        spoiled = {
            s["ballot_serial"] for s in self.board.get("spoils", [])
        }
        m = self.config.candidate_count
        columns: List[List[ElGamalCiphertext]] = [[] for _ in range(m)]
        for ballot in self.board.get("ballots", []):
            if ballot["ballot_serial"] in spoiled:
                continue
            for ct in ballot["ciphertexts"]:
                i = ct["candidate_index"]
                columns[i].append(
                    ElGamalCiphertext(
                        alpha=int(ct["alpha"], 16),
                        beta=int(ct["beta"], 16),
                    )
                )
        return columns


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def _empty_board() -> Dict[str, Any]:
    """The 12 SPEC section 14 top-level keys, all empty."""
    return {
        "election_config": {},
        "base_hash": "",
        "trustee_setup": {},
        "authority_keys": {},
        "prepoll": {},
        "ballots": [],
        "spoils": [],
        "poll_register": {},
        "schedule_opening": {},
        "tally_aggregate": {},
        "decryption_transcript": {},
        "tally_declaration": {},
    }


def _derive_schedule(
    seed: bytes,
    ballots_expected: int,
    num: int,
    den: int,
) -> set[int]:
    """SPEC 10.2: serial s is a test ballot iff

        B2I(SHA-256(L("EVOTE-TESTDRAW-v1") || seed || U64(s))[0:8]) * den
            < num * 2^64

    Each serial is drawn independently, so the number of test ballots
    varies around num/den * N rather than being fixed. Exact integer
    arithmetic; no floating point reaches the comparison.
    """
    picks: set[int] = set()
    for s in range(1, ballots_expected + 1):
        digest = hashlib.sha256(
            L("EVOTE-TESTDRAW-v1") + seed + s.to_bytes(8, "big")
        ).digest()
        if int.from_bytes(digest[:8], "big") * den < num * 2**64:
            picks.add(s)
    return picks
